### ISSUE TITLE
array display issue?

### ISSUE THREAD

**Issue by kransom14** [monogenea/CNNtutorial#1]
When I run the following code to check the second cat after array restructure, I get the following image. 
```
# Fix structure for 2d CNN
train_array <- t(trainData$X)
dim(train_array) <- c(50, 50, nrow(trainData$X), 1)
# Reorder dimensions
train_array <- aperm(train_array, c(3,1,2,4))

test_array <- t(testData)
dim(test_array) <- c(50, 50, nrow(testData), 1)
# Reorder dimensions
test_array <- aperm(test_array, c(3,1,2,4))

# Check cat again
testCat <- train_array[1,,,]
image(t(apply(testCat, 2, rev)), col = gray.colors(12),
      axes = F)
```
![array_check](https://user-images.githubusercontent.com/18158438/54151106-47acc980-43f7-11e9-8198-9e7cda2751a0.jpeg)

**Comment by monogenea** [comment]
Hi @kransom14 ,
That is exactly what you should see. Compare this to the actual picture (printed a few steps before) and you will see they are the same - albeit this one as 50 x 50 pixels. If you are not happy with this resolution you can try increasing to 100 x 100 pixels (a lot more computationally intensive). Let me know if it makes sense now.

**Comment by kransom14** [comment]
Now I see it, thank you! I was expecting to see the image of the second cat, where here you print the first cat. It's obvious now that I look at the first cat image.

**Comment by monogenea** [comment]
You are right, in `testCat <- train_array[1,,,]` it should read `testCat <- train_array[2,,,]`. Can you confirm this please, so that I will change the code accordingly? Thanks for raising this

**Comment by kransom14** [comment]
Yes that is correct, thank you!

**Comment by monogenea** [comment]
Script updated as per above
